setx = {"green", "blue"}
sety = {"blue", "yellow"}
print("Original set elements:")
print(setx)
print(sety)
print("\nIntersection of to said sets")
setz=setx.intersection(sety)
print(setz)
setz1=setx.union(sety)
print(setz1)
setz2=setx.difference(sety)
print(setz2)
setz3=sety.difference(setx)
print(setz3)
setz4=setx.symmetric_difference(sety)
print(setz4)